version: '3.8'
services:
  docker-inception-build:
    image: demo/docker-inception-build:outer
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./inception:/inception